import type { AsyncTaskStatus } from '@runapi.ai/core';

// --- Models ---

export type GrokImagineTextToVideoModel = 'grok-imagine-text-to-video';
export type GrokImagineImageToVideoModel = 'grok-imagine-image-to-video';
export type GrokImagineTextToImageModel = 'grok-imagine-text-to-image';
export type GrokImagineImageToImageModel = 'grok-imagine-image-to-image';

// --- Enums ---

export type GrokImagineAspectRatio = '2:3' | '3:2' | '1:1' | '16:9' | '9:16';
export type GrokImagineMode = 'fun' | 'normal' | 'spicy';
export type GrokImagineResolution = '480p' | '720p';
export type GrokImagineExtendTimes = '6' | '10';

// --- Common ---

interface TaskCommonParams {
  /** URL for completion callback notifications. */
  callback_url?: string;
}

// --- Text to Video ---

export interface GrokImagineTextToVideoParams extends TaskCommonParams {
  model: GrokImagineTextToVideoModel;
  /** Text description of desired video motion, up to 5000 characters. */
  prompt: string;
  /** Width-to-height ratio of the generated video. Default: 2:3. */
  aspect_ratio?: GrokImagineAspectRatio;
  /** Generation mode. fun / normal / spicy. Default: normal. */
  mode?: GrokImagineMode;
  /** Duration in seconds (6-30). */
  duration?: number;
  /** Output resolution. Default: 480p. */
  resolution?: GrokImagineResolution;
  /** Disable content filtering when set to false. Default: false. */
  nsfw_checker?: boolean;
}

// --- Image to Video ---

interface ImageToVideoBase extends TaskCommonParams {
  model: GrokImagineImageToVideoModel;
  /** Optional text description for the desired motion. */
  prompt?: string;
  mode?: GrokImagineMode;
  duration?: number;
  resolution?: GrokImagineResolution;
  aspect_ratio?: GrokImagineAspectRatio;
  nsfw_checker?: boolean;
}

/** Image-to-video using external image URLs. */
export interface GrokImagineImageToVideoUrlParams extends ImageToVideoBase {
  /** Reference image URL array with exactly one URL. Mutually exclusive with task_id. */
  image_urls: string[];
  task_id?: never;
  index?: never;
}

/**
 * Image-to-video using a prior text-to-image task_id.
 * Runs image-to-video against one of the 6 images generated by that task.
 */
export interface GrokImagineImageToVideoTaskParams extends ImageToVideoBase {
  /** Task id from a prior grok-imagine text-to-image task. */
  task_id: string;
  /** 0-based index (0-5) selecting which generated image to use. */
  index?: number;
  image_urls?: never;
}

export type GrokImagineImageToVideoParams =
  | GrokImagineImageToVideoUrlParams
  | GrokImagineImageToVideoTaskParams;

// --- Text to Image ---

export interface GrokImagineTextToImageParams extends TaskCommonParams {
  model: GrokImagineTextToImageModel;
  /** Text description of desired image content, up to 5000 characters. */
  prompt: string;
  /** Width-to-height ratio of the generated image. Default: 1:1. */
  aspect_ratio?: GrokImagineAspectRatio;
  /** Disable content filtering when set to false. Default: false. */
  nsfw_checker?: boolean;
  /** Enable quality mode (slower but higher precision). Default: false. */
  enable_pro?: boolean;
}

// --- Image to Image ---

export interface GrokImagineImageToImageParams extends TaskCommonParams {
  model: GrokImagineImageToImageModel;
  /** Optional text prompt describing the desired output. */
  prompt?: string;
  /** Reference image URL array (exactly one URL). */
  image_urls: string[];
  nsfw_checker?: boolean;
}

// --- Extend ---

export interface GrokImagineExtendParams extends TaskCommonParams {
  /** Task id from a prior grok-imagine video generation task. */
  task_id: string;
  /** Text description of the desired motion for the extended segment. */
  prompt: string;
  /** Starting position of the extension (seconds into the original video). */
  extend_at: number | string;
  /** Duration of the extension in seconds: 6 or 10. */
  extend_times: GrokImagineExtendTimes | 6 | 10;
}

// --- Upscale ---

export interface GrokImagineUpscaleParams extends TaskCommonParams {
  /** Task id from a prior grok-imagine video generation task. */
  task_id: string;
}

// --- Responses ---

export interface TaskCreateResponse {
  id: string;
}

export interface MediaUrl {
  url: string;
}

export interface GrokImagineVideoResponse {
  id: string;
  status: AsyncTaskStatus;
  videos?: MediaUrl[];
  error?: string;
  [key: string]: unknown;
}

export interface GrokImagineImageResponse {
  id: string;
  status: AsyncTaskStatus;
  images?: MediaUrl[];
  error?: string;
  [key: string]: unknown;
}

export type CompletedGrokImagineVideoResponse = GrokImagineVideoResponse & {
  status: 'completed';
  videos: MediaUrl[];
};

export type CompletedGrokImagineImageResponse = GrokImagineImageResponse & {
  status: 'completed';
  images: MediaUrl[];
};
