import type { AsyncTaskStatus } from '@runapi.ai/core';

// --- Models ---

export type GrokImagineTextToVideoModel = 'grok-imagine-text-to-video';
export type GrokImagineImageToVideoModel = 'grok-imagine-image-to-video';
export type GrokImagineVideo15FastModel = 'grok-imagine-video-1.5-fast';
export type GrokImagineVideo15PreviewModel = 'grok-imagine-video-1.5-preview';
export type GrokImagineTextToImageModel = 'grok-imagine-text-to-image';
export type GrokImagineEditImageModel = 'grok-imagine-edit-image';

// --- Enums ---

export type GrokImagineAspectRatio = '2:3' | '3:2' | '1:1' | '16:9' | '9:16';
export type GrokImagineFastAspectRatio = GrokImagineAspectRatio;
export type GrokImaginePreviewAspectRatio = GrokImagineAspectRatio | 'auto';
export type GrokImagineMotionStyle = 'fun' | 'normal' | 'spicy';
export type GrokImagineResolution = '480p' | '720p';
export type GrokImagineFastResolution = GrokImagineResolution;
export type GrokImagineExtensionDurationSeconds = 6 | 10;

// --- Common ---

interface TaskCommonParams {
  /** URL for completion callback notifications. */
  callback_url?: string;
}

// --- Text to Video ---

interface TextToVideoBase extends TaskCommonParams {
  /** Output resolution. Default: 480p. */
  output_resolution?: GrokImagineResolution;
}

export interface GrokImagineTextToVideoClassicParams extends TextToVideoBase {
  model: GrokImagineTextToVideoModel;
  /** Text description of desired video motion, up to 5000 characters. */
  prompt: string;
  /** Width-to-height ratio of the generated video. Default: 2:3. */
  aspect_ratio?: GrokImagineAspectRatio;
  /** Motion style preset. Default: normal. */
  motion_style?: GrokImagineMotionStyle;
  /** Duration in seconds (6-30). */
  duration_seconds?: number;
  /** Content safety check toggle. */
  enable_safety_checker?: boolean;
}

export interface GrokImagineTextToVideoPreviewParams extends TextToVideoBase {
  model: GrokImagineVideo15PreviewModel;
  /** Text description of desired video motion, up to 4096 characters. */
  prompt: string;
  /** Width-to-height ratio of the generated video. Default: auto. */
  aspect_ratio?: GrokImaginePreviewAspectRatio;
  /** Duration in seconds (1-15). Default: 8. */
  duration_seconds?: number;
  motion_style?: never;
  enable_safety_checker?: never;
}

export interface GrokImagineTextToVideoFastParams extends TaskCommonParams {
  model: GrokImagineVideo15FastModel;
  /** Text description of desired video motion. */
  prompt: string;
  /** Optional reference images used to guide the generated video. */
  reference_image_urls?: string[];
  /** Width-to-height ratio of the generated video. */
  aspect_ratio?: GrokImagineFastAspectRatio;
  /** Duration in seconds (1-30). Default: 8. */
  duration_seconds?: number;
  /** Output resolution. Default: 480p. */
  output_resolution?: GrokImagineFastResolution;
  motion_style?: never;
  enable_safety_checker?: never;
}

export type GrokImagineTextToVideoParams =
  | GrokImagineTextToVideoClassicParams
  | GrokImagineTextToVideoFastParams
  | GrokImagineTextToVideoPreviewParams;

// --- Image to Video ---

interface ImageToVideoClassicBase extends TaskCommonParams {
  model: GrokImagineImageToVideoModel;
  /** Optional text description for the desired motion. */
  prompt?: string;
  motion_style?: GrokImagineMotionStyle;
  duration_seconds?: number;
  output_resolution?: GrokImagineResolution;
  aspect_ratio?: GrokImagineAspectRatio;
  enable_safety_checker?: boolean;
}

/** Image-to-video using an external image URL. */
export interface GrokImagineImageToVideoUrlParams extends ImageToVideoClassicBase {
  /** Source image URL. Mutually exclusive with source_task_id. */
  source_image_url: string;
  source_task_id?: never;
  index?: never;
}

/**
 * Image-to-video using a prior text-to-image task.
 * Runs image-to-video against one of the 6 images generated by that task.
 */
export interface GrokImagineImageToVideoTaskParams extends ImageToVideoClassicBase {
  /** Task id from a prior grok-imagine text-to-image task. */
  source_task_id: string;
  /** 0-based index (0-5) selecting which generated image to use. */
  index?: number;
  source_image_url?: never;
}

export interface GrokImagineImageToVideoPreviewParams extends TaskCommonParams {
  model: GrokImagineVideo15PreviewModel;
  /** Source image URL. */
  source_image_url: string;
  /** Optional text description for the desired motion, up to 4096 characters. */
  prompt?: string;
  aspect_ratio?: GrokImaginePreviewAspectRatio;
  /** Duration in seconds (1-15). Default: 8. */
  duration_seconds?: number;
  output_resolution?: GrokImagineResolution;
  source_task_id?: never;
  index?: never;
  motion_style?: never;
  enable_safety_checker?: never;
}

export interface GrokImagineImageToVideoFastParams extends TaskCommonParams {
  model: GrokImagineVideo15FastModel;
  /** Source image URL. */
  source_image_url: string;
  /** Optional reference images used to guide the generated video. */
  reference_image_urls?: string[];
  /** Optional text description for the desired motion. */
  prompt?: string;
  aspect_ratio?: GrokImagineFastAspectRatio;
  /** Duration in seconds (1-30). Default: 8. */
  duration_seconds?: number;
  /** Output resolution. Default: 480p. */
  output_resolution?: GrokImagineFastResolution;
  source_task_id?: never;
  index?: never;
  motion_style?: never;
  enable_safety_checker?: never;
}

export type GrokImagineImageToVideoParams =
  | GrokImagineImageToVideoUrlParams
  | GrokImagineImageToVideoTaskParams
  | GrokImagineImageToVideoFastParams
  | GrokImagineImageToVideoPreviewParams;

// --- Text to Image ---

export interface GrokImagineTextToImageParams extends TaskCommonParams {
  model: GrokImagineTextToImageModel;
  /** Text description of desired image content, up to 5000 characters. */
  prompt: string;
  /** Width-to-height ratio of the generated image. Default: 1:1. */
  aspect_ratio?: GrokImagineAspectRatio;
  /** Content safety check toggle. */
  enable_safety_checker?: boolean;
  /** Enable quality mode (slower but higher precision). Default: false. */
  enable_pro?: boolean;
}

// --- Edit Image ---

export interface GrokImagineEditImageParams extends TaskCommonParams {
  model: GrokImagineEditImageModel;
  /** Optional text prompt describing the desired output. */
  prompt?: string;
  /** Source image URL. */
  source_image_url: string;
  enable_safety_checker?: boolean;
}

// --- Extend ---

export interface GrokImagineExtendParams extends TaskCommonParams {
  /** Task id from a prior grok-imagine video generation task. */
  source_task_id: string;
  /** Text description of the desired motion for the extended segment. */
  prompt: string;
  /** Starting position of the extension (seconds into the original video). */
  start_seconds: number;
  /** Duration of the extension in seconds: 6 or 10. */
  extension_duration_seconds: GrokImagineExtensionDurationSeconds;
}

// --- Upscale ---

export interface GrokImagineUpscaleParams extends TaskCommonParams {
  /** Task id from a prior grok-imagine video generation task. */
  source_task_id: string;
}

// --- Responses ---

export interface TaskCreateResponse {
  id: string;
}

export interface MediaUrl {
  url: string;
}

export interface GrokImagineVideoResponse {
  id: string;
  status: AsyncTaskStatus;
  videos?: MediaUrl[];
  error?: string;
  [key: string]: unknown;
}

export interface GrokImagineImageResponse {
  id: string;
  status: AsyncTaskStatus;
  images?: MediaUrl[];
  error?: string;
  [key: string]: unknown;
}

export type CompletedGrokImagineVideoResponse = GrokImagineVideoResponse & {
  status: 'completed';
  videos: MediaUrl[];
};

export type CompletedGrokImagineImageResponse = GrokImagineImageResponse & {
  status: 'completed';
  images: MediaUrl[];
};
